title: Diffraction Microstructure Imaging in 3D
description: Project's website
google_analytics: 
show_downloads: false
# theme: jekyll-theme-slate
remote_theme: poole/lanyon

gems:
  - jekyll-mentions
